### ISSUE TITLE
move template to file

### ISSUE THREAD

**Issue by 54m** [go-generalize/repo_generator#12]
名前どうするか
提案コメントください

ディレクトリ作るなら`templates`?

拡張子決めたい
`templates/???.(gtpl/tmpl/tpl/template/etc)`

上記???に当てはまるファイル名
`tmplConst` -> 
`tmplLabel` -> 
`tmpl` ->

**Comment by moezakura** [comment]
Goと同じ階層にxxx.go.tmpl という形式で他の箇所では作ってたと思うのでそれでどうでしょう？

**Comment by 54m** [comment]
> Goと同じ階層にxxx.go.tmpl という形式で他の箇所では作ってたと思うのでそれでどうでしょう？

@moezakura 
ディレクトリにはまとめたいと思うので
`templates/xxx.go.tmpl` とか？

**Comment by tsuzu** [comment]
拡張子にtemplateを入れるのであればtmplはファイルにいらないかなと思っています
それ以外は良さそう
statikとか使う想定ですかね
